repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.72.1
    hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_validate
    # - id: terraform_checkov
    - id: terraform_docs
      args:
        - '--args=--hide providers --sort-by required'

  - repo: https://github.com/pecigonzalo/pre-commit-terraform-vars
    rev: v1.0.0
    hooks:
    - id: terraform-vars

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: terraform.tfstate

  # https://www.conventionalcommits.org/en/v1.0.0/#specification
  # https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies: ['@commitlint/config-conventional']
